=== digitalrisedorset/magento-subscription-module/etc/subscription_plans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:annotation>
            <xs:documentation>The root node for sections configuration</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plans">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="plan" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="label" type="xs:string" />
                                        <xs:element name="discount" type="xs:integer" />
                                        <xs:element name="frequency" type="xs:string" />
                                        <xs:element name="terms" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== digitalrisedorset/magento-subscription-module/etc/subscription_plans.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="urn:magento:module:Drd_Subscribe:etc/subscription_plans.xsd">
    <plans>
        <plan id="weekly_10">
            <label>Weekly - 10% Off</label>
            <discount>10</discount>
            <frequency>1w</frequency>
            <terms>subscription_tos_v2</terms>
        </plan>
        <plan id="monthly_5">
            <label>Monthly - 5% Off</label>
            <discount>5</discount>
            <frequency>1m</frequency>
            <terms>subscription_tos_v2</terms>
        </plan>
    </plans>
</config>
